name: 'string-transform'
description: 'GitHub action for manipulating strings'
author: 'Sergey Zwezdin'

branding:
  icon: 'align-justify'
  color: 'purple'

inputs:
  source:
    description: 'Source string'
    required: true
  transform:
    description: 'String transformations'
    required: true
    default: 'lower'

outputs:
  var:
    description: 'Transformed string'

runs:
  using: node20
  main: dist/index.js
